### ISSUE TITLE
Implement input validation for Start Time, End Time fields in Get new and.... trigger

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/salesforce-component-v2#15]
**Description:** `End Time` input value cannot be equal or less then `Start Time`
STR:
1. Create flow with Get new and.... trigger: select object, input same values for Start Time, End Time fields
2. start flow or retrireve sample

AR: nothing found by trigger. Sample retrieve fails (timeout)
ER: error thrown when Start Time value >= End Time value

**Comment by if0s** [comment]
August 30, 2022, we presented new `Get New and Updated Objects Polling` trigger, old one set to deprecated.
Ca't reproduce on updated version

**Comment by andrewreshitko** [comment]
closed according to the comment above.
