### ISSUE TITLE
Touch Up Salesforce

### ISSUE THREAD

**Issue by A3a3e1** [elasticio/salesforce-component-v2#18]
Inspect the component if it complies OIH

**Comment by shulkaolka** [comment]
The component was checked for compliance with the OIH standard
1. Get New and Updated Objects Polling trigger: config fields `Output method` and `Include linked objects` are present (not included at OIH standard)
2. Custom triggers: `Query` `Subscribe to platform events`
3. Custom actions: `Bulk Create/Update/Delete/Upsert`, `Subscribe to platform events`, `Bulk Query`
4. `Delete Object (at most 1)` - complies with the standard (both iteration)
5. `Lookup Object (at most 1)` - complies with the standard (both iteration)
6. `Lookup Objects` - complies with the OIH standard
7. `Upsert Object` - complies with the OIH standard
8. `Create Object` - complies with the OIH standard

Can be implemented:
1. Make RAW Request
2. Lookup Set Of Objects By Unique Criteria

**Comment by shulkaolka** [comment]
Suggestions for component improvement:
1. Do refactor (at least entry.js file)
2. Add more test - coverage report:



| File                                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line |                                              
| --------------------------------------- | --------- | ---------- | --------- | --------- | -------------------------------------------------------------------- |
|All files                              |   90.57 |    73.46 |   89.62 |   90.96 |                                                                    
salesforce-component-v2               |     100 |      100 |     100 |     100 |                                                                    
verifyCredentials.js                 |     100 |      100 |     100 |     100 |                                                                    
salesforce-component-v2/lib           |   77.69 |    69.44 |   68.92 |      80 |                                                                    
common.js                            |     100 |       75 |     100 |     100 | 3                                                                  
entry.js                             |   75.71 |       65 |      40 |   76.12 | 9,13-14,30-31,43-48,54-55,72,84,90-91                              
salesForceClient.js                  |    81.3 |     81.4 |   77.19 |    81.9 | 49,57,73,96-97,103,124,150-153,172,192,208-213,233-234,244-245,253
util.js                              |   71.93 |    52.38 |   41.67 |   80.39 | 13-20,29-31                                                        
salesforce-component-v2/lib/actions   |   79.18 |    62.22 |   83.78 |   79.11 |                                                                    
bulk_cud.js                          |   68.18 |       40 |   57.14 |   68.18 | 9-18,27-28,47,72-74,80-116                                         
bulk_q.js                            |   89.47 |       50 |     100 |   89.47 | 21-22                                                              
createObject.js                      |     100 |      100 |     100 |     100 |                                                                    
deleteObject.js                      |   66.67 |    47.06 |      60 |   65.96 | 8,12-13,68-74,91-97,106-107                                        
lookupObject.js                      |   65.22 |    47.83 |   85.71 |   65.67 | 69-75,87-90,96-97,106-112,129-135                                  
lookupObjects.js                     |    93.2 |    81.48 |     100 |      93 | 24,28,95,143,220-221,232                                           
query.js                             |   86.21 |    71.43 |     100 |   86.21 | 9,17,27,38                                                         
upsert.js                            |   71.88 |       25 |     100 |   71.88 | 44-50,59-62                                                        
salesforce-component-v2/lib/helpers   |   93.12 |       80 |   95.56 |   93.64 |                                                                    
attachment.js                        |    93.1 |    69.23 |     100 |   96.23 | 55,90                                                              
lookupCache.js                       |   95.77 |    77.78 |     100 |   95.65 | 58-59,140                                                          
utils.js                             |   89.47 |    86.67 |   88.89 |   88.89 | 48,60-65,69,85-86,163                                              
wrapper.js                           |   95.24 |    83.33 |     100 |   95.24 | 54,62                                                              
salesforce-component-v2/lib/triggers  |   68.18 |    36.36 |     100 |   68.18 |                                                                    
query.js                             |   68.18 |    36.36 |     100 |   68.18 | 11-15,18,30                                                        
salesforce-component-v2/spec          |   91.78 |    64.29 |   84.21 |   91.43 |                                                                    
common.js                            |   91.18 |    64.29 |   81.82 |   90.32 | 53,84,89                                                           
util.spec.js                         |   84.21 |      100 |      80 |   84.21 | 27-34                                                              
verifyCredentials.spec.js            |     100 |      100 |     100 |     100 |                                                                    
salesforce-component-v2/spec/actions  |   97.49 |    84.71 |   97.81 |   97.54 |                                                                    
bulk_cud.spec.js                     |     100 |      100 |     100 |     100 |                                                                    
bulk_q.spec.js                       |     100 |      100 |     100 |     100 |                                                                    
createObject.spec.js                 |     100 |      100 |     100 |     100 |                                                                    
deleteObject.spec.js                 |   78.38 |       68 |   81.25 |   79.17 | 65,69,78,90-92,199-216                                             
lookupObject.spec.js                 |     100 |    92.59 |     100 |     100 | 216-259                                                            
lookupObjects.spec.js                |   99.16 |    82.09 |     100 |   99.14 | 126,208                                                            
query.spec.js                        |     100 |      100 |     100 |     100 |                                                                    
upsert.spec.js                       |     100 |    90.91 |     100 |     100 | 138-189                                                            
salesforce-component-v2/spec/helpers  |   97.98 |      100 |    97.5 |   97.98 |                                                                    
attachment.spec.js                   |    87.1 |      100 |    87.5 |    87.1 | 79-86                                                              
lookupCache.spec.js                  |     100 |      100 |     100 |     100 |                                                                    
utils.spec.js                        |     100 |      100 |     100 |     100 |                                                                    
wrapper.spec.js                      |     100 |      100 |     100 |     100 |                                                                    
salesforce-component-v2/spec/triggers |     100 |      100 |     100 |     100 |                                                                    
entry.spec.js                        |     100 |      100 |     100 |     100 |                                                                    
query.spec.js                        |     100 |      100 |     100 |     100 |

**Comment by shulkaolka** [comment]
@jhorbulyk is it enough for the scope of this issue?

**Comment by A3a3e1** [comment]
Once we cover the code with tests it may also make sense to refactor the code. As it looks quite complex

**Comment by andrewreshitko** [comment]
Also need to include improvements:
* Replace Steward with Maester (in action Lookup Object (at most 1) and may be for others)
* Implement/Test correct work with Salesforce Files (ContentDocument) for all actions/triggers
* Component should be able to handle attachment information via the message body

**Comment by HannaTrotsenko** [comment]
- [ ] `Version Data` must be required
![image](https://github.com/elasticio/salesforce-component-v2/assets/28867440/30c03272-1ba4-4ec1-a774-cb7299854d1f)

- [ ] qa

**Comment by if0s** [comment]
Required fields depends on information provided directly from Salesforce, I don't know why, but this field (`Version Data`) marked as "nillable" (can be null):
![image](https://github.com/elasticio/salesforce-component-v2/assets/7985390/97a9c49d-ce2d-4e2e-bf43-7ab435df1f86)

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/salesforce-component-v2/releases/tag/2.7.0
