### ISSUE TITLE
Fix upload attachment body size limit in salesforce-component-v2

### ISSUE THREAD

**Issue by olegosh** [elasticio/salesforce-component-v2#21]
In the salesforce-component-v2 I found the same bug as this:
https://app.zenhub.com/workspaces/ps-development-59bbb52d21e82e515786af83/issues/elasticio/component-commons-library/41
Where **maxContentLength** should be changed to **maxBodyLength** inside method uploadAttachment, because of the reasons explained before in the previous bug report (see link)

**Comment by andrewreshitko** [comment]
not relevant anymore
