### ISSUE TITLE
The log  message"Got secret Going to fetch secret" goes to loop after setting "Size of Polling Page" and "Max Fetch Count"  values different from default at "Get New and Updated Objects Polling" trigger

### ISSUE THREAD

**Issue by HannaTrotsenko** [elasticio/salesforce-component-v2#32]
# Component Bug Report

## Description

The log  message"Got secret Going to fetch secret" goes to loop after setting "Size of Polling Page" and "Max Fetch Count"  values different from default at "Get New and Updated Objects Polling" trigger

## Component Version

rev: 774992527a45ae7e46ca5b2d11ec9618353fa5c5
21.41
qa@elastic.io]

## Steps to Reproduce

1. Set `Salesforce v2` as trigger
2. Choose `Get New and Updated Objects Polling` trigger
3. Choose `Contact` in `Object` field 
4. Set any values `Size of Polling Page` and `Max Fetch Count` (I used 2 and 3)
5. Retreive sample

## Actual Result
The log  message"Got secret Going to fetch secret" goes to loop and retrieve sample failed with timeout
![image](https://user-images.githubusercontent.com/28867440/137710311-f3caf768-1c6a-4b99-beb6-c1c879756cce.png)

## Expected Result

Samples retreive in the count according to the `Size of Polling Page` and `Max Fetch Count`  values

## Workaround(s)

Use Query `trigger` ?

**Comment by if0s** [comment]
August 30, 2022, we presented new `Get New and Updated Objects Polling` trigger, old one set to deprecated
