### ISSUE TITLE
The "INVALID_SESSION_ID: Session expired or invalid" error after verifying secret which isn't used in the flow 

### ISSUE THREAD

**Issue by HannaTrotsenko** [elasticio/salesforce-component-v2#6]
#  Bug report

STR:
1. Create new secret for Salesforce V2 component and pay attention that it isn't used in the flows
2. Wait a few hours
3. Create new flow, choose Salesforce V2 component and verify this secret

AR:
The error in the logs
```
Going to make request describeGlobal() for verifying credentials...
Got error:  INVALID_SESSION_ID: Session expired or invalid
    at HttpApi.getError (/home/apprunner/node_modules/jsforce/lib/http-api.js:250:13)
    at /home/apprunner/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/home/apprunner/node_modules/promise/lib/core.js:37:12)
    at /home/apprunner/node_modules/promise/lib/core.js:123:15
    at flush (/home/apprunner/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errorCode: 'INVALID_SESSION_ID'
}
going to refresh secret
Error: Request failed with status code 400 Failed to refresh token
```

4. Choose this secret and configure any function of this component
5. Retrieve sample

AR=ER: sample is retrieved successfully

**Comment by shulkaolka** [comment]
The described problem reproduced on rest-api-component v2 as well.
But after investigation, it was found that Ctrl + F5 fixes this problem. Looks like incoming configurations for verifyCredentials module takes from the cache.

**Comment by shulkaolka** [comment]
It was reproduced one more time with the following steps:
1. Create a secret for Salesforce V2 component using OAuth2 App where expiration time less than 1 hour (15 minutes)
2. Wait for 16 minutes
3. Try to verify credentials
AR: Error `INVALID_SESSION_ID` and credentials can't be verified, but if retrieve sample with this creds - it is successful

The reason for this is:
1. SaleaForce doesn't send `expires_in` property and there is used standard time = 3600 at Faceless service
2. SalesForce component couldn't force refresh token cause configuration (credentials) at **_verifyCredentials_** module doesn't include `secretId` that is required for the refreshing token method at Faceless service

**Comment by zuker** [comment]
@shulkaolka pls set default expiry time for salesforce auth client https://api.elastic.io/docs/v2/#create-auth-client `attributes.credentials.token_expires_in` this will enable automatic token refreshes for secrets of this auth client.
