### ISSUE TITLE
Improve execution/error handling for the "Subscribe to platform events" trigger

### ISSUE THREAD

**Issue by MykytaDuniashev** [elasticio/salesforce-component-v2#68]
## Description

Currently, only the first execution is relevant and contains logs, all others do nothing, it will increase logs and credentials retrieving numbers. We can only monitor errors for the flow by logs, logs will have a link to the execution which contains and will contain all future messages and errors. But since we store executions only for 30 days, and after 30 days the first execution will simply disappear we need to improve this trigger. It should work as all other triggers work, not store all messages/errors logs in one execution which becomes unavailable after some period of time. It should store each new message or error in a new execution, instead of creating a useless one.

## Component Version

2.7.0

## Definition of done

- [ ] Redo the saving messages/errors logs logic

**Comment by MykytaDuniashev** [comment]
With this improvement please add additional logs to check a connection to the Salesforce. FYI @if0s

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/salesforce-component-v2/releases/tag/2.7.1

**Comment by MykytaDuniashev** [comment]
Issue solved. [Slack conversation](https://elasticio.slack.com/archives/CADMT8CCD/p1695637000368959?thread_ts=1695305869.665919&cid=CADMT8CCD).
