### ISSUE TITLE
Investigate the possibility of implementing Salesforce PKCE

### ISSUE THREAD

**Issue by MykytaDuniashev** [elasticio/salesforce-component-v2#75]
## Description

Salesforce changed the checked fields on their end when creating a Connected App.
![image](https://github.com/elasticio/salesforce-component-v2/assets/108279772/8dd6fb50-b85e-4754-a7bd-978d7ed3ae4a)
Since `Require Proof Key for Code Exchange (PKCE) Extension for Supported Authorization Flows` is a default setting now, investigate if it is possible to implement it on our component. Currently, this field is not necessary and can be manually disabled during the app creation process.

These two fields are also default:
- Require Secret for Web Server Flow	
- Require Secret for Refresh Token Flow

While the required field `Enable Authorization Code and Credentials Flow` which is not the default, should be enabled manually.

**Comment by if0s** [comment]
Component use built in to platform OAuth 2.0 feature (**Faceless**) for authorization, and it **doesn't support PKCE**.
To implement this, we will need to make our own realization, and it's really not as easy to do with this component.

I've tested other default options (without PKCE) and it works fine:
![image](https://github.com/elasticio/salesforce-component-v2/assets/7985390/64778750-a97a-4a04-b508-51bf5704668b)
