### ISSUE TITLE
Investigate & Add OIH Trigger: Subscribe to platform events (Pub/Sub API)

### ISSUE THREAD

**Issue by andrewreshitko** [elasticio/salesforce-component-v2#76]
# New OIH Action or Trigger: {Action/Trigger Name}
[OIH Standard](https://github.com/elasticio/Connectors/blob/master/Adapters/AdapterBehaviorStandardization/StandardizedActionsAndTriggers.md#{Section})

## Config Fields
* Platform Event name 

## Output Metadata
* Event description

## Related API Documentation
* [Links to related API documentation](https://developer.salesforce.com/docs/platform/pub-sub-api/overview)

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/salesforce-component-v2/releases/tag/2.8.0
