### ISSUE TITLE
Possibility to extend APEX REST functionality into Salesforce component

### ISSUE THREAD

**Issue by Glico21** [elasticio/salesforce-component-v2#82]
# Other Feature Request

## Description

Some clients use the custom salesforce functionality like [apexrest endpoints](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_rest_intro.htm). They use different requests in different basePath which started from `services/apexrest/` when salesforce component using only path with `service/data/`.
We need to figure out if we can implement apexrest functionality into our component without losing the current functionality of the component.

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/salesforce-component-v2/releases/tag/2.8.3
