### ISSUE TITLE
Bugs in `Get New and Updated Objects Polling` trigger (limit 10000 records + undefined LastModifiedDate )

### ISSUE THREAD

**Issue by if0s** [elasticio/salesforce-component-v2#86]
# Component Bug Report

## Description

Issues in `Get New and Updated Objects Polling` trigger:
  * Emit only one batch of messages if results are more than 10000
  * Error `Cannot read properties of undefined (reading 'LastModifiedDate')` if you used and delete `Size of Polling Page` value

## Component Version

2.8.4

### Emit only one batch of messages if results are more than 10000:
1. Use `Get New and Updated Objects Polling` trigger for object that has more than 10000 records
2. Don't use `Process Single Page Per Execution` checkbox
3. Run the flow

### Error `Cannot read properties of undefined (reading 'LastModifiedDate')` if you used and delete `Size of Polling Page` value:
1. Set any value to `Size of Polling Page` in `Get New and Updated Objects Polling` trigger
2. Save the flow
3. Edit flow and delete value from `Size of Polling Page`

### Emit only one batch of messages if results are more than 10000:
Emitted only first butch of messages

### Error `Cannot read properties of undefined (reading 'LastModifiedDate')` if you used and delete `Size of Polling Page` value:
Got error `Cannot read properties of undefined (reading 'LastModifiedDate')`

### Emit only one batch of messages if results are more than 10000:
Emitted all records

### Error `Cannot read properties of undefined (reading 'LastModifiedDate')` if you used and delete `Size of Polling Page` value:
No errors

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/salesforce-component-v2/releases/tag/2.8.5

**Comment by MarianaZaloha** [comment]
https://github.com/elasticio/salesforce-component-v2/releases/tag/2.8.5
